### ISSUE TITLE
Blockchain in Python

### ISSUE THREAD

**Issue by kmader** [pydatazrh/meetup#31] opened 2017-10-02 07:10 UTC
Not sure how clickbait friendly this group is, but I really enjoyed this article and project (https://hackernoon.com/learn-blockchains-by-building-one-117428612f46?gi=22fca9a00cda) and accompanying repository (https://github.com/dvf/blockchain) and I think having a tutorial on it could be interesting / potentially attract quite a few new people. Plus actually writing a bit of code goes a long way to demystifying the endless hype.

**Comment by betatim** [comment] 2017-10-02 08:02
I'd be interested. Not having read the article I suspect we'd make this the exclusive topic of a meetup?

cc @d-simon

**Comment by betatim** [comment] 2017-10-06 06:08
I'd like to try out having a one hour meetup where we try and go through this as a group. Maybe for the December meetup as "Christmas special". Maybe have three speakers that work as a team instead of just one.

How could we organise it so that people who are new to blockchain and/or not super fit in python still get something out of it? Maybe we live code it between the three speakers, and people in the room can run it. Try to modify the history of the blockchain, etc instead of everyone trying to code it interactively?

I'd be up for being one of the three people.

**Comment by kmader** [comment] 2017-10-12 16:19
I would also be willing to present, it also looks like we should be able to do some interactive demos with binder as long as we run everything on the local machine. I've adapted their example for kaggle so it runs the standard CURL commands to show how everything works (https://www.kaggle.com/kmader/slightly-more-advanced-blockchain/)

**Comment by wolfv** [comment] 2017-10-13 11:08
@Leonidaz0r has some Blockchain experience at ETH.

**Comment by markusbaden** [comment] 2017-10-14 10:53
Would be interested too

**Comment by betatim** [comment] 2017-11-16 07:39
@kmader and others who would like to contribute to running this event: how do we get organised? We should announce this meetup soon, which means we need a bit of an idea who can make it from our side and what we plan on doing.

I would propose the following:

The meetup will be in the style of a tutorial. Some slides, some live coding, time for participants to code, slides, live coding, participants code, ... repeat. We follow the DIY blockchain article from https://github.com/pydatazrh/meetup/issues/31#issue-261998336 If we manage to cover steps 1, 2 and 3 we will be doing well I think. Leave step 4 for people to try at home, maybe demo it with some prepared code/nodes. Getting everyone on the same wifi so their laptops can talk to each other (ETH wifi ops probably has that firewalled) is a project++ by itself.

This means we need to make a shared set of slides on google docs, split up the code into good sections, and have a run through at some point to see how far away from 60minutes we are.

What do you think?

**Comment by jakeret** [comment] 2017-11-16 08:23
Sounds like a good plan. Agree, we should announce that thing asap.

Three steps - three speakers (@betatim, @kmader, @markusbaden)? 

We haven't settled on a date yet. betatim proposed some dates in an other discussion (#33). Unfortunately, I can't make it then.
How about the **Wed. 13. December**? 
@betatim  could you ping ETH for a room as soon as we know the date?

**Comment by betatim** [comment] 2017-11-16 11:31
@TitusCornelius suggested he has a contact at DigiComp. Our ETH contact isn't at ETH for a while -> no room.

13.12. would also work for me as a date. To bring the discussion from #33 over here (so we stay on topic) I suggested 12.12. as preferred date, 14.12. as backup, but also fine with 13.12.

**Comment by markusbaden** [comment] 2017-11-17 13:18
Happy to contribute as speaker or as helper. Worked through the original post and it's actually quite fun. 

12.12, 13.12. And 14.12.  Work for me

**Comment by betatim** [comment] 2017-11-17 15:57
So should we make 13.12. the preferred date? @jakeret are you interested in being a helper/speaker/leader for this? If yes we'd have three people and can announce the meetup. If no then we should wait to announce until we have three. (We can announce and then swap someone afterwards, just want to avoid having only two people lead this session)

**Comment by kmader** [comment] 2017-11-17 17:27
13.12 works for me, I also have a few routers I could bring if we want to test things there or could probably run everything on EC2 nodes using repo2docker or something like that. If people pregister we could setup everything in advance

**Comment by TitusCornelius** [comment] 2017-11-17 18:40
I havent heard back yet, but let‘s announce asap with the program and the
location as TBD..

should know by Monday if it works out

**Comment by TitusCornelius** [comment] 2017-11-17 18:42
TBD only regarding location of course

**Comment by jakeret** [comment] 2017-11-17 19:26
>**X-max special: Build your own Blockchain**
>
>Christmas is approaching and Santa has something very special for all the PyDatonions in his gift bag! 
>Always wondered why everyone is so hyped about Blockchain? How does it work under the hood? Who needs a Blockchain anyway?
>
>This time we’re going to have a hands-on session on this topic. Our speakers will team up and by implementing our own chain together we will explore the nitty-gritty details.

**Comment by TitusCornelius** [comment] 2017-11-17 19:30
sounds amazing 😉 so sad I can’t come 😔🙁

**Comment by betatim** [comment] 2017-11-18 08:21
Some slight edits to the announcement. I think we should encourage people to bring their own laptop fully kitted out. 👍 to bringing wifi routers, but I would try and design it so we do not need the internet/wifi for a successful tutorial (more like cherry on top bonus).

>**X-max special: Build your own Blockchain**
>
>Christmas is approaching and Santa has something very special for all the PyDatonions in his gift bag! 
>Always wondered why everyone is so hyped about Blockchain? How does it work under the hood? Who needs a Blockchain anyway?
>
>This time we’re going to have a hands-on session on this topic. Our speakers will team up and by implementing our own chain together we will explore the nitty-gritty details. This meetup will be a tutorial style meetup so please bring your own laptop with `python` 3, `flask` v0.12.2, and `requests` v2.18.4 installed and running.

**Comment by betatim** [comment] 2017-11-18 08:32
Should we be presumptuous and assume yy-uge interest -> limit sign ups? How to deal with those that say they will come but never update their RSVP? Should we instead say "We will lock the door once the room is (too) full, so be early if you want to be sure to get a seat"?

**Comment by sredford** [comment] 2017-11-18 09:17
X-max -> Xmas ? or is this a joke I don't get?

What will actually happen at the meetup is not clear to me from reading the announcement. 
> Our speakers will team up and by implementing our own chain together we will explore the nitty-gritty details. 
could be read as the speakers are demonstrating the block chain, while the audience watches.

What about:
**Xmas special: Build your own Blockchain**

Christmas is approaching and Santa has something very special for all the PyDataZuris in his sack! Always wondered why everyone is so hyped about Blockchain? How does it work under the hood? Who needs a Blockchain anyway?

This time we’re going to have a hands-on session. Our speakers will lead a tutorial. You on your laptop will build your own Blockchain. No prior experience is necessary, but please arrive with python 3, flask v0.12.2, and requests v2.18.4 installed and running.

**Comment by jakeret** [comment] 2017-11-18 09:24
This thing is gaining momentum. Perfect! 👍 I like @sredford 's adaptions.
@betatim  Do we expect a lot of people do show up, considering it's close to Christmas? For the August meetup I had set an upper limit on meetup.com and people then seemed to take the RSVP more seriously

**Comment by jakeret** [comment] 2017-11-18 09:33
I've created a draft on meetup.com. Should we publish it and update the location as soon as we know more?

**Comment by betatim** [comment] 2017-11-20 06:17
I'd wait to see if we get a location update from @TitusCornelius during the morning and then publish without/with one this afternoon??

Maybe I am over-thinking it with the RSVP.

**Comment by TitusCornelius** [comment] 2017-11-20 15:01
Hope to get an answer by tmr, guy seems to be busy..

**Comment by TitusCornelius** [comment] 2017-11-20 15:53
alright! CONFIRMED!

could someone put the meetup online? i'm in the middle of sth right now..

>>>
Hallo Titus

Sorry, bin grad voll Land unter, darum habe ich mich noch nicht gemeldet.

Ja am 13.12. sollte das klappen. Ihr könnt das MEetup bei uns machen.

Dann können wir da auch gleich über weitere Zusammenarbeit reden.
Location zum einbinden: https://www.digicomp.ch/standorte/zuerich
Kannst du uns dann den LLink zur Meetup Event page noch senden?

Joe, bitte bei dir eintragen das wir am 13.12. ein  Meetup bei uns haben.

Herzlichen Dank
LG Lorenz

**Comment by TitusCornelius** [comment] 2017-11-20 21:50
all right, still got to it. SCHEDULED! good job everyone :D

**Comment by betatim** [comment] 2017-11-20 21:52
Meetup scheduled and public.

**Comment by jakeret** [comment] 2017-11-21 07:39
And filling up really quickly 👍

**Comment by TitusCornelius** [comment] 2017-11-21 08:25
2 spots left, that was quick...

we should be strict about people canceling if they can‘t come, so that
people can slip in from the waiting list. Maybe we should send out a
message about that.

**Comment by betatim** [comment] 2017-11-21 10:03
I would make it "first come first seated" on the day. At least it is far too tedious to get people to actually cancel their RSVP, then print off a list, check names at the door, etc.

Also, how big is the room? :)

**Comment by Sebubu** [comment] 2017-11-21 16:35
I would prefer "first come first seated" too because there are always people which sign but don't show up.

The second reason is that it's already full after not even a day and I didn't get a place :grinning:

**Comment by betatim** [comment] 2017-11-22 22:06
@TitusCornelius could you put us (Tim, Joel) all in touch with Lorenz from Digicomp?

Thoughts on trying to increase the size of the room? I'd be -0 on more than 50 attendees as it will make it more of a lecture and less interactive if we get too far from 1 helper per 10 participants (by that math the ideal number would be 30)

**Comment by jakeret** [comment] 2017-11-23 07:06
I would also stick with the current number. If we look for a larger room there'll always be one who is not getting a seat and opting for an even larger room.

Based on the meetup experience there are always some signing up but not showing up. So I guess we will get close this ideal number

**Comment by Sebubu** [comment] 2017-11-26 13:20
Do you need another helper at the pydata blockchain special? I saw on meetup that you are worried about too few helpers. I know how a blockchain works and some people mingle I can program python pretty well.

**Comment by Sebubu** [comment] 2017-11-29 06:09
According to the almost non existing reaction, I guess no further help is needed?

**Comment by betatim** [comment] 2017-11-29 06:47
I'd take the lack of reaction as a positive: no one objects :)

**Comment by betatim** [comment] 2017-11-29 07:06
I'd take the lack of reaction as a positive: no one objects :)

To get the ball rolling [the beginning of slides](https://docs.google.com/presentation/d/1GaoGagHTQYcABOVAgY40T1SVCzFKpH6H_4T8jVZlnsU/edit?usp=sharing). Mostly followed the structure of [the article](https://hackernoon.com/learn-blockchains-by-building-one-117428612f46) for the moment. Each orange slide is meant as "you do something now": live coding, audience typing, audience running things. For the transitions to not be too abrupt I would say 10min per orange section as typical time?

**Comment by jakeret** [comment] 2017-11-29 07:29
@Sebubu, sorry for not replying. Help is very welcome. I guess as soon as
we're preparing thing it will become much more clear where support is
needed.

Thanks Tim for bringing momentum into this thing!
I would suggest that we aim at an two hour session. Atm we have 5*10min of
coding session. This leaves plenty of time to explain things.
Any suggestion on how to split things up? Any preferences?

**Comment by betatim** [comment] 2017-11-29 07:37
I'd try and aim to be done in 90m, with some time left for people to play by themselves/questions. Also we will over run ... :)

I'd suggest we have one laptop setup and connected. Introduce all four helpers at the start, one of us drives the laptop, the other three circulate around the room to help people who get stuck. Then we swap driver after ~1/4 of the time?

**Comment by Sebubu** [comment] 2017-11-29 18:34
That's going to be a sportive event if we want to do it within 90min incl. coding.
How do we want to split up the talk?

**Comment by betatim** [comment] 2017-11-29 21:24
Add some breakpoints you like. I think that is something to do once we have a better feeling how much content there is to each slide. I'd also be fine with us just swapping "live" when we feel like it.

Sportlich ist gut! Keeps you on your toes.

**Comment by betatim** [comment] 2017-11-29 21:25
(The link tot he slides let's you edit them, so make use of that power.)

**Comment by jakeret** [comment] 2017-11-30 15:09
I've [adapted](https://github.com/jakeret/blockchain_pydatazrh) the original code such that the API is exposed in a swagger ui. If we push this to a cloud service we would have our first blockchain node with an ui.

**Comment by betatim** [comment] 2017-11-30 22:23
Are we confident enough that there will be working internet in the room for everyone? We should also check with the host if nodes on the network can reach each other (if we want to do "now connect to your neighbours node"). Often conference wifis are configured to let you connect out but not to other devices on the network.

---

@jakeret your idea is that people eventually all connect to the same blockchain and we have the whole room together? And we use the cloud one as the "seed"? I think that would be cool. For your "cloud service" will heroku do?

**Comment by jakeret** [comment] 2017-12-05 19:23
I'm about to push this to heroku. Should be online soon

Anyway, time is running. There are just a few days left for preparation. @kmader @markusbaden @betatim What is the overall status? Is there anything we should discuss / split up / delegate?

**Comment by TitusCornelius** [comment] 2017-12-05 19:39
@jakeret @betatim I forwarded you the email with the contact of Lorenz @
Digicomp Academy

**Comment by jakeret** [comment] 2017-12-06 13:08
@TitusCornelius thanks just saw it.

The app is on heroku: https://blockchain-pydatazrh.herokuapp.com/#/default

**Comment by betatim** [comment] 2017-12-07 06:52
I was working through the code yesterday to make some snippets to build up some of the ideas in part one (what is a chain, block, POW, etc). I will make a PR to your repo @jakeret to add some snippets tonight.

One thing that I didn't understand: why is the hash of the previous block not part of the POW calculation?

**Comment by Sebubu** [comment] 2017-12-07 08:24
I'm going to explain the consensus algorithm if nobody has already captured it.

**Comment by Sebubu** [comment] 2017-12-07 08:47
Hey guys,
@betatim and I were talking about a short pre-meetup of the helpers. We currently are all working on different parts of the presentation and the purpose of this pre-meetup is to ensure a consistent presentation and not 4 single presentations in a row which leave important parts out.

Proposal: Tuesday, 5pm, Hiltl Sihlpost

I please every helper to give a short answer if he can attend this meetup.

**Comment by betatim** [comment] 2017-12-07 15:30
I have time for meeting up on Tuesday and think it would be pretty useful to get everything synced (and us looking good on Wednesday evening)

**Comment by markusbaden** [comment] 2017-12-07 17:51
:+1: 

I can make it on Tuesday.

**Comment by jakeret** [comment] 2017-12-07 19:36
Yeah sounds good. I'm in as well.

I can do the first part, intro, setting the scene, big picture

**Comment by kmader** [comment] 2017-12-07 21:22
Tuesday works for me too, but the night of the meetup, I'll have to leave early, so if possible I'd do more of the intro stuff, otherwise I am perfectly ok with just helping with the slides

**Comment by jakeret** [comment] 2017-12-11 07:16
@kmader go ahead. It's fine with me if you do the intro

I just finished my few slides on the API

**Comment by betatim** [comment] 2017-12-11 10:32
Two things from my side:

* the hosts would prefer if we had an apero break earlier than 2h after starting. So we should design a nice natural break point into the work. ~60minutes in maybe? Maybe do the distributed part in the second half?

* I am stuck in London because of bad weather, currently I am on a flight that should get me to Zurich in time for our meeting on Tuesday but they have been cancelling flights all day today, so they might cancel flights tomorrow as well. I'll keep you posted.

**Comment by betatim** [comment] 2017-12-11 10:37
To get a decision back to the hosts as quickly as possible I will tell them that we will schedule a break after 60m unless someone speaks out here against it. I'll send the email this evening (after EOB)

**Comment by betatim** [comment] 2017-12-12 12:43
I will spend some time now working on the slides and material. @kmader added some links and comments to the slides (not sure if all of you get the notifications?). Following up on them I think we should use the time of the tutorial to build up a version of `blockchain.py` on people's laptops that they can run, fiddle with, join the global blockchain. IMHO Binder and notebooks would be nice because low barrier to entry but harder to use for people because you need some "magic" to start a flask from a notebook and then have the right binder magic to forward the ports etc. So I would go with a low tech approach of text files and python REPL and link notebooks etc as extra material as "extra reading".

**Comment by betatim** [comment] 2017-12-13 14:46
https://github.com/pydatazrh/christmas_special_2017 link to the repo for tonight.

I was about to add a few challenges to each notebook for people to have something to guide them during the "now you do something" parts. However I'm starting to think that it is better if we reach the apero after say 53minutes than if we overrun to 70 or 75minutes. So I'd vote no challenges. I think with the extra kaggle notebooks and links we have we give people enough to look at after the meetup if they want to.

**Comment by betatim** [comment] 2017-12-15 09:05
Thank you everyone for making this happen!

**Closed by betatim** 2017-12-15 09:05 UTC

**Comment by kmader** [comment] 2017-12-20 08:54
As a last note, to really really get down to the 'heart' of bitcoin, [this](http://www.righto.com/2014/09/mining-bitcoin-with-pencil-and-paper.html) article brings you all the way down to pencil and paper
